#
#server:
#  port: 8080
#logging:
#  level:
#    cn.itcast: debug
#spring:
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/itcast_travel
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: ytroot
#mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
##    map-underscore-to-camel-case: true
#  type-aliases-package: cn.itcast.pojo
#
