server:
  port: 8084
spring:
  application:
    name: page-service
  thymeleaf:
    cache: false
  spring:
    rabbitmq:
      host: 192.168.153.65
      username: leyou
      password: root
      virtual-host: leyou
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka