server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/itcast_travel
    username: root
    password: ytroot
  application:
    name: user-service
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9090/eureka,http://127.0.0.1:9091/eureka
    registry-fetch-interval-seconds: 30
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90