server:
  port: 8082
spring:
  application:
    name: upload-service
  servlet:
    multipart:
      max-file-size: 5MB #限制文件上传的大小
      max-request-size: 10MB #单次请求大小限制

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
   ip-address: 127.0.0.1
   prefer-ip-address: true
fdfs:
  connect-timeout: 600
  so-timeout: 2500
  thumb-image: #缩略图
    height: 60
    width: 60
  tracker-list: #tracker地址
    - 192.168.153.65:22122
